variables:
  REGISTRY: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com
  REPOSITORY: doikota/weather-app
  IMAGE_TAG: 1.0.2

default:
  image: node

stages:
  - Build

build:
  stage: Build
  image: node
  services:
    - docker
  script:
    - npm install -D webpack-cli
    - npm run test
    - npm run build
    - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $REGISTRY
    - docker build . -t $REPOSITORY
    - docker tag $REPOSITORY:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
    - docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
