variables:
  REGISTRY: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com
  REPOSITORY: doikota/weather-app
  IMAGE_TAG: 1.0.2

default:
  image: public.ecr.aws/sam/build-nodejs20.x

stages:
  - Build
  - Container

build:
  stage: Build
  script:
    - npm install -D webpack-cli
    - npm run test
    - npm run build
  artifacts:
    paths:
      - dist/*

container:
  stage: Container
  services:
    - docker:24.0
  script:
    - aws configure
    - aws ecr get-login-password --region ap-northeast-1
    - docker build . -t $REPOSITORY
    - docker tag $REPOSITORY:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
    - docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
