variables:
  AWS_ACCOUNT_ID: 718624127210
  REGISTRY: 718624127210.dkr.ecr.ap-northeast-1.amazonaws.com
  REPOSITORY: doikota/weather-app
  IMAGE_TAG: 1.0.2
  AWS_IAM_ROLE: arn:aws:iam::718624127210:role/gitlab-openidconnect-role

default:
  image: public.ecr.aws/sam/build-nodejs20.x

stages:
  - Build
  - Assume

build:
  stage: Build
  script:
    - npm install -D webpack-cli
    - npm run test
    - npm run build
  artifacts:
    paths:
      - dist/*

assume:
  stage: Assume
  image:
    name: docker:latest
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  services:
    - docker:dind
  script:
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 718624127210.dkr.ecr.ap-northeast-1.amazonaws.com
    - docker build . -t $REPOSITORY
    - docker tag $REPOSITORY:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
    - docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
