variables:
  AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
  REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com
  REPOSITORY: doikota/weather-app
  IMAGE_TAG: 1.0.2
  AWS_IAM_ROLE: arn:aws:iam::$AWS_ACCOUNT_ID:role/gitlab-openidconnect-role

default:
  image: public.ecr.aws/sam/build-nodejs20.x

stages:
  - Build
  - Container

build:
  stage: Build
  script:
    - npm install -D webpack-cli
    - npm run test
    - npm run build
  artifacts:
    paths:
      - dist/*

assume:
  stage: Container
  image:
    name: docker:latest
  # id_tokens:
  #   GITLAB_OIDC_TOKEN:
  #     aud: https://gitlab.com
  services:
    - docker:dind
  script:
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $REGISTRY
    - docker build . -t $REPOSITORY
    - docker tag $REPOSITORY:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
    - docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
