image: atlassian/default-image:4

variables:
  CONTAINER: doikota/weather-app
  IMAGE_TAG: 1.0.5

pipelines:
  default:
    - step:
        services:
          - docker
        name: 'Install and Build'
        oidc: true
        script:
          # # variables
          # - export CONTAINER='doikota/weather-app'
          # - export IMAGE_TAG='1.0.5'
          # frontend
          - npm install -D webpack-cli
          - npm run test
          - npm run build
          # container
          - docker build -t $CONTAINER:$IMAGE_TAG .
          # openid connect
          - pipe: atlassian/aws-ecr-push-image:2.3.0
            variables:
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              AWS_OIDC_ROLE_ARN: $AWS_IAM_ROLE_ARN
              IMAGE_NAME: $CONTAINER
              TAGS: $IMAGE_TAG
