image: atlassian/default-image:4

pipelines:
  default:
    - step:
        services:
          - docker
        name: 'Install and Build'
        oidc: true
        script:
          # variables
          - export CONTAINER='doikota/weather-app'
          - export IMAGE_TAG='1.0.5'
          # - export IAM_ROLE_ARN='arn:aws:iam::718624127210:role/golden-openidconnect-role'
          # frontend
          - npm install -D webpack-cli
          - npm run test
          - npm run build
          # container
          - docker build -t $CONTAINER .
          - docker tag $CONTAINER:latest $CONTAINER:$IMAGE_TAG
          # openid connect
          - pipe: atlassian/aws-ecr-push-image:2.3.0
            variables:
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              AWS_OIDC_ROLE_ARN: $AWS_IAM_ROLE_ARN
              IMAGE_NAME: $CONTAINER
              TAGS: $IMAGE_TAG
