image: atlassian/default-image:4

pipelines:
  default:
    - step:
        services:
          - docker
        name: 'Install and Build'
        oidc: true
        script:
          # variables
          - export CONTAINER='doikota/weather-app'
          - export IMAGE_TAG='1.0.0'
          - export IAM_ROLE_ARN='arn:aws:iam::718624127210:role/golden-openidconnect-role'
          - echo $CONTAINER
          - echo $IMAGE_TAG
          - echo $IAM_ROLE_ARN
          # frontend
          - npm install -D webpack-cli
          - npm run build
          # container
          - docker build -t $CONTAINER .
          - docker tag $CONTAINER:latest $CONTAINER:$IMAGE_TAG
          # openid connect
          - pipe: atlassian/aws-ecr-push-image:2.3.0
            variables:
              AWS_DEFAULT_REGION: 'ap-northeast-1'
              AWS_OIDC_ROLE_ARN: $IAM_ROLE_ARN
              IMAGE_NAME: $CONTAINER
              TAGS: $IMAGE_TAG
        # name: Deploy
        # script:
        #   - pipe: atlassian/aws-eks-kubectl-run:2.8.0
        #     variables:
        #       CLUSTER_NAME: 'golden-cluster'
        #       KUBECTL_COMMAND: 'apply'
        #       RESOURCE_PATH: 'kubernetes/frontend-deployment.yml'
        #       DEBUG: 'true'
        #   - pipe: atlassian/aws-eks-kubectl-run:2.8.0
        #     variables:
        #       CLUSTER_NAME: 'golden-cluster'
        #       KUBECTL_COMMAND: 'apply'
        #       RESOURCE_PATH: 'kubernetes/frontend-service.yml'
        #       DEBUG: 'true'
        #   - pipe: atlassian/aws-eks-kubectl-run:2.8.0
        #     variables:
        #       CLUSTER_NAME: 'golden-cluster'
        #       KUBECTL_COMMAND: 'apply'
        #       RESOURCE_PATH: 'kubernetes/frontend-loadbalancer.yml'
        #       DEBUG: 'true'
        #   - pipe: atlassian/aws-eks-kubectl-run:2.8.0
        #     variables:
        #       CLUSTER_NAME: 'golden-cluster'
        #       KUBECTL_COMMAND: 'apply'
        #       RESOURCE_PATH: 'kubernetes/frontend-ingress.yml'
        #       DEBUG: 'true'
        #   - pipe: atlassian/aws-eks-kubectl-run:2.8.0
        #     variables:
        #       CLUSTER_NAME: 'golden-cluster'
        #       KUBECTL_COMMAND: 'expose'
        #       DEBUG: 'true'
        #       KUBECTL_ARGS:
        #         - 'deployment'
        #         - 'frontend-deployment'
        #         - '--type'
        #         - 'LoadBalancer'
        #         - '-n'
        #         - 'golden-frontspace'
