version: 1.0

env:
  variables:
    DOCKER_BUILDKIT: '1'
    LOCATION: '718624127210.dkr.ecr.ap-northeast-1.amazonaws.com'
    CONTAINER: 'doikota/weather-app'
    REPOSITORY: '718624127210.dkr.ecr.ap-northeast-1.amazonaws.com/doikota/weather-app'
    IMAGE_TAG: '1.0.1'

phases:
  build:
    commands:
      - echo $LOCATION
      - echo $CONTAINER
      - echo $REPOSITORY
      - echo $IMAGE_TAG
      # frontend
      - npm install -D webpack-cli
      - npm run build
      # container
      - aws ecr get-login-password | docker login --username AWS --password-stdin $LOCATION
      - docker build -t $CONTAINER .
      - docker tag $CONTAINER:latest $REPOSITORY:$IMAGE_TAG
      - docker push $REPOSITORY:$IMAGE_TAG
