name: GitHub Actions for Weather
run-name: ${{ github.actor }} is building up Weather Application
on: [push]

env:
  CONTAINER: weather-app
  REPOSITORY: doikota/weather-app
  IMAGE_TAG: 1.0.1

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build Client
        run: |
          npm install -D webpack-cli
          npm run test
          npm run build

      # AWS認証
      - name: AWS Credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-duration-seconds: 1200

      # コンテナビルド
      - name: Build Container
        run: |
          docker build -t $CONTAINER .
          docker tag $CONTAINER:latest $REPOSITORY:$IMAGE_TAG
        # docker push $REPOSITORY:$IMAGE_TAG

      # ECR認証
      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v1

      # Buildx Setup がサブディレクトリ利用には必要
      - name: Buildx Setup
        uses: docker/setup-buildx-action@v3

      # コンテナイメージPush
      - name: Buildx Setup
        uses: docker/build-push-action@v5
        with:
          push: true
          #tags: '$REPOSITORY:$IMAGE_TAG'
          tags: doikota/weather-app:1.0.1
          context: '{{defaultContext}}:'
